"""
Brand color configuration for Suomen Palikkaharrastajat ry.

Colors are hardcoded LEGO® color values cross-referenced against the Rebrickable
palette (colors.csv in the project root, for reference only — not read by code).
To change the palette, edit the values here — everything is regenerated by `make`.

Rebrickable ID reference: https://rebrickable.com/colors/
"""

# ── Logo mark colors (minifig head) ──────────────────────────────────────────
# Rebrickable #14 - Yellow
FACE_COLOR      = '#F2CD37'

# Rebrickable #0 - Black
FEATURE_COLOR   = '#05131D'

# Rebrickable #15 - White  (eye highlights)
HIGHLIGHT_COLOR = '#FFFFFF'

# ── Subtitle text colors ──────────────────────────────────────────────────────
SUBTITLE_ON_LIGHT = '#05131D'   # Dark text on light backgrounds
SUBTITLE_ON_DARK  = '#FFFFFF'   # White text on dark backgrounds

# ── Association name ──────────────────────────────────────────────────────────
ASSOCIATION_NAME = 'Suomen Palikkaharrastajat ry'

# ── Subtitle color per variant ────────────────────────────────────────────────
# Maps variant stem (as used in filenames) to subtitle text color.
# Variants intended for dark backgrounds use white text; others use dark text.
SUBTITLE_COLOR = {
    'minifig-yellow': SUBTITLE_ON_LIGHT,
    'minifig-black':  SUBTITLE_ON_LIGHT,
    'minifig-white':  SUBTITLE_ON_DARK,
}
