{-# LANGUAGE OverloadedStrings #-}

-- | Generate public/brand.css — the canonical CSS design system file.
-- Consumer projects copy this file locally and @import it in their CSS.
-- Note: Tailwind v4 requires @theme to be in the locally-processed file;
-- importing from a CDN URL does not propagate @theme tokens.
module Guide.CssGen (generateBrandCss) where

import Guide.Colors
import Guide.DesignData
import Data.Text (Text)
import qualified Data.Text as T
import Data.Maybe (mapMaybe)
import Numeric (showFFloat)

generateBrandCss :: Text
generateBrandCss = T.concat
    [ cssHeader
    , cssFontFace
    , cssTheme
    , cssTypeUtilities
    , cssBaseLayer
    , cssReducedMotion
    , cssSharedComponents
    ]

-- ---------------------------------------------------------------------------
-- Header
-- ---------------------------------------------------------------------------

cssHeader :: Text
cssHeader = T.unlines
    [ "/* brand.css \x2014 Suomen Palikkaharrastajat ry design system"
    , " * Generated by brand-gen. Consumer projects import this file locally."
    , " * Do NOT import from a CDN URL \x2014 Tailwind v4 requires @theme to be in the"
    , " * locally processed file. Copy this file and import it in your project CSS."
    , " */"
    , ""
    ]

-- ---------------------------------------------------------------------------
-- @font-face
-- ---------------------------------------------------------------------------

cssFontFace :: Text
cssFontFace = T.unlines
    [ "@font-face {"
    , "  font-family: \"Outfit\";"
    , "  src: url(\"fonts/Outfit-VariableFont_wght.ttf\") format(\"truetype\");"
    , "  font-weight: 100 900;"
    , "  font-style: normal;"
    , "  font-display: swap;"
    , "}"
    , ""
    ]

-- ---------------------------------------------------------------------------
-- @theme block
-- ---------------------------------------------------------------------------

cssTheme :: Text
cssTheme = T.unlines $
    [ "@theme {"
    , "  /* \x2500\x2500 Brand core \x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500 */"
    , "  --color-brand:              " <> hexText featureColor <> ";"
    , "  --color-brand-yellow:       #FAC80A;"
    , "  --color-brand-red:          " <> semHex "colorBrandRed" <> ";"
    , ""
    , "  /* \x2500\x2500 Nougat palette \x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500 */"
    ] ++ nougatLines ++
    [ ""
    , "  /* \x2500\x2500 Semantic text \x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500 */"
    , "  --color-text-primary: " <> semHex "colorTextPrimary" <> ";"
    , "  --color-text-on-dark: " <> semHex "colorTextOnDark" <> ";"
    , "  --color-text-muted:   " <> semHex "colorTextMuted" <> ";"
    , "  --color-text-subtle:  " <> semHex "colorTextSubtle" <> ";"
    , ""
    , "  /* \x2500\x2500 Semantic backgrounds \x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500 */"
    , "  --color-bg-page:   " <> semHex "colorBgPage" <> ";"
    , "  --color-bg-dark:   " <> semHex "colorBgDark" <> ";"
    , "  --color-bg-subtle: " <> semHex "colorBgSubtle" <> ";"
    , "  --color-bg-accent: " <> semHex "colorBgAccent" <> ";"
    , ""
    , "  /* \x2500\x2500 Semantic borders \x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500 */"
    , "  --color-border-default: " <> semHex "colorBorderDefault" <> ";"
    , "  --color-border-brand:   " <> semHex "colorBorderBrand" <> ";"
    , ""
    , "  /* \x2500\x2500 Typography \x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500 */"
    , "  --font-sans: \"Outfit\", system-ui, sans-serif;"
    , ""
    , "  /* \x2500\x2500 Motion \x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500 */"
    ] ++ durationLines ++ easingLines ++
    [ "}"
    , ""
    ]

nougatLines :: [Text]
nougatLines = mapMaybe mkLine
    [ ("light-nougat", "  --color-brand-nougat-light: ")
    , ("nougat",        "  --color-brand-nougat:       ")
    , ("dark-nougat",   "  --color-brand-nougat-dark:  ")
    ]
  where
    mkLine (sid, prop) = case filter (\(i, _, _) -> i == sid) skinTones of
        ((_, _, Hex h) : _) -> Just $ prop <> h <> ";"
        _                   -> Nothing

semHex :: Text -> Text
semHex name = case filter (\(n, _, _, _, _, _) -> n == name) semanticColors of
    ((_, _, h, _, _, _) : _) -> h
    _                         -> "#000000"

durationLines :: [Text]
durationLines = mapMaybe mkLine
    [ ("fast", "  --duration-fast: ")
    , ("base", "  --duration-base: ")
    , ("slow", "  --duration-slow: ")
    ]
  where
    mkLine (name, prop) = case filter (\(n, _, _, _) -> n == name) motionDurationData of
        ((_, ms, _, _) : _) -> Just $ prop <> T.pack (show ms) <> "ms;"
        _                   -> Nothing

easingLines :: [Text]
easingLines = mapMaybe mkLine
    [ ("standard",   "  --ease-standard:   ")
    , ("decelerate", "  --ease-decelerate: ")
    , ("accelerate", "  --ease-accelerate: ")
    ]
  where
    mkLine (name, prop) = case filter (\(n, _, _, _, _, _) -> n == name) motionEasingData of
        ((_, p1x, p1y, p2x, p2y, _) : _) ->
            Just $ prop <> "cubic-bezier("
                <> fmtD p1x <> ", " <> fmtD p1y <> ", "
                <> fmtD p2x <> ", " <> fmtD p2y <> ");"
        _ -> Nothing

-- ---------------------------------------------------------------------------
-- @utility type-* blocks
-- ---------------------------------------------------------------------------

cssTypeUtilities :: Text
cssTypeUtilities = T.unlines $
    [ "/* \x2500\x2500 Typography scale \x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500 */"
    , ""
    ] ++ concatMap renderTypeUtility typeScale

renderTypeUtility :: TypeScaleRow -> [Text]
renderTypeUtility (name, w, sr, _, lh, ls, cssClass, _) =
    [ "@utility " <> cssClass <> " {"
    , "  font-size: " <> fmtD sr <> "rem;"
    , "  font-weight: " <> T.pack (show w) <> ";"
    , "  line-height: " <> fmtD lh <> ";"
    ]
    ++ extraProps name ls
    ++ [ "}", "" ]
  where
    extraProps "Overline" ls'
        = "  text-transform: uppercase;"
        : [ "  letter-spacing: " <> fmtD ls' <> "em;" | ls' /= 0 ]
    extraProps "Mono" ls'
        = [ "  letter-spacing: " <> fmtD ls' <> "em;" | ls' /= 0 ]
        ++ [ "  font-family: ui-monospace, monospace;" ]
    extraProps _ ls'
        = [ "  letter-spacing: " <> fmtD ls' <> "em;" | ls' /= 0 ]

-- ---------------------------------------------------------------------------
-- @layer base
-- ---------------------------------------------------------------------------

cssBaseLayer :: Text
cssBaseLayer = T.unlines
    [ "/* \x2500\x2500 Base \x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500 */"
    , ""
    , "@layer base {"
    , "  body {"
    , "    font-family: var(--font-sans);"
    , "  }"
    , "}"
    , ""
    ]

-- ---------------------------------------------------------------------------
-- Reduced-motion
-- ---------------------------------------------------------------------------

cssReducedMotion :: Text
cssReducedMotion = T.unlines
    [ "/* \x2500\x2500 Reduced-motion \x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500 */"
    , ""
    , "@media (prefers-reduced-motion: reduce) {"
    , "  *, *::before, *::after {"
    , "    animation-duration: 0.01ms !important;"
    , "    transition-duration: 0.01ms !important;"
    , "  }"
    , "  .logo-animated {"
    , "    display: none;"
    , "  }"
    , "}"
    , ""
    ]

-- ---------------------------------------------------------------------------
-- Shared component classes
-- ---------------------------------------------------------------------------

cssSharedComponents :: Text
cssSharedComponents = T.unlines
    [ "/* \x2500\x2500 Shared components \x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500 */"
    , ""
    , "@media (prefers-reduced-motion: no-preference) {"
    , "  .card-hover:hover {"
    , "    transform: translateY(-2px);"
    , "    transition: transform var(--duration-base) var(--ease-standard);"
    , "  }"
    , "}"
    , ""
    , ".timeline-nav {"
    , "  scrollbar-width: thin;"
    , "  scrollbar-color: var(--color-border-default) transparent;"
    , "}"
    , ""
    , ".timeline-nav::-webkit-scrollbar {"
    , "  width: 6px;"
    , "}"
    , ""
    , ".timeline-nav::-webkit-scrollbar-thumb {"
    , "  background-color: var(--color-border-default);"
    , "  border-radius: 3px;"
    , "}"
    ]

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

-- Format a Double for CSS: fixed notation, no scientific notation, no trailing zeros.
-- Examples: 3.0 -> "3", 1.875 -> "1.875", -0.02 -> "-0.02", 0.08 -> "0.08"
fmtD :: Double -> Text
fmtD d = T.pack (stripZeros (showFFloat (Just 6) d ""))
  where
    stripZeros s
        | '.' `elem` s = reverse . dropWhile (== '.') . dropWhile (== '0') . reverse $ s
        | otherwise    = s
