{-# LANGUAGE OverloadedStrings #-}

-- | Generate src/Brand/Tokens.elm — the single Elm source of truth for all
-- brand design constants. Modify Guide.Colors or Guide.DesignData in Haskell,
-- then run `make run` to regenerate this file and design-guide.json together.
module Guide.ElmGen (generateBrandModule) where

import Guide.Colors
import Guide.DesignData
import Data.Text (Text)
import qualified Data.Text as T

generateBrandModule :: Text
generateBrandModule = T.unlines $
    [ "module Guide.Tokens exposing (..)"
    , ""
    , "-- Generated by logo-gen. Do not edit by hand."
    , "-- Single Elm source for all brand design constants."
    , "-- To modify: change src/Brand/Colors.hs or src/Brand/DesignData.hs, then run `make run`."
    , ""
    , "-- ---------------------------------------------------------------------------"
    , "-- Organisation"
    , "-- ---------------------------------------------------------------------------"
    , ""
    , "associationName : String"
    , "associationName ="
    , "    " <> q associationName
    , ""
    , "logoBaseUrl : String"
    , "logoBaseUrl ="
    , "    " <> q "https://logo.palikkaharrastajat.fi"
    , ""
    , "designGuideUrl : String"
    , "designGuideUrl ="
    , "    " <> q "/design-guide.json"
    , ""
    , "-- ---------------------------------------------------------------------------"
    , "-- Brand colors (primitive)"
    , "-- ---------------------------------------------------------------------------"
    , ""
    , "colorBrandBlack : String"
    , "colorBrandBlack ="
    , "    " <> q (unHex featureColor)
    , ""
    , "colorBrandWhite : String"
    , "colorBrandWhite ="
    , "    " <> q (unHex highlightColor)
    , ""
    , "colorBrandYellow : String"
    , "colorBrandYellow ="
    , "    " <> q "#FAC80A"
    , ""
    , "-- ---------------------------------------------------------------------------"
    , "-- Semantic colors"
    , "-- ---------------------------------------------------------------------------"
    ]
    ++ concatMap renderSemanticColor semanticColors ++
    [ ""
    , "-- ---------------------------------------------------------------------------"
    , "-- Skin tones"
    , "-- ---------------------------------------------------------------------------"
    , ""
    , "type alias SkinTone ="
    , "    { id : String, name : String, hex : String }"
    , ""
    , "skinTones : List SkinTone"
    , "skinTones ="
    , renderSkinToneList skinTones
    , ""
    , "-- ---------------------------------------------------------------------------"
    , "-- Rainbow"
    , "-- ---------------------------------------------------------------------------"
    , ""
    , "type alias RainbowColor ="
    , "    { id : String, name : String, hex : String, description : String }"
    , ""
    , "rainbowColors : List RainbowColor"
    , "rainbowColors ="
    , renderRainbowList rainbowColors
    , ""
    , "-- ---------------------------------------------------------------------------"
    , "-- Typography"
    , "-- ---------------------------------------------------------------------------"
    , ""
    , "fontFamily : String"
    , "fontFamily ="
    , "    " <> q "Outfit, system-ui, sans-serif"
    , ""
    , "fontFile : String"
    , "fontFile ="
    , "    " <> q "/fonts/Outfit-VariableFont_wght.ttf"
    , ""
    , "type alias TypeStyle ="
    , "    { name : String"
    , "    , weight : Int"
    , "    , sizePx : Int"
    , "    , sizeRem : Float"
    , "    , lineHeight : Float"
    , "    , letterSpacingEm : Float"
    , "    , cssClass : String"
    , "    , description : String"
    , "    }"
    , ""
    , "typeScale : List TypeStyle"
    , "typeScale ="
    , renderTypeScaleList typeScale
    ]
    ++ concatMap renderTypeHelper typeScale ++
    [ ""
    , "-- ---------------------------------------------------------------------------"
    , "-- Spacing"
    , "-- ---------------------------------------------------------------------------"
    , ""
    , "spacingBaseUnit : Int"
    , "spacingBaseUnit ="
    , "    4"
    , ""
    , "type alias SpacingStep ="
    , "    { name : String, px : Int, rem : Float, tailwindClass : String, description : String }"
    , ""
    , "spacingScale : List SpacingStep"
    , "spacingScale ="
    , renderSpacingList spacingScale
    , ""
    , "pageWrapper : String"
    , "pageWrapper ="
    , "    " <> q pageWrapperClass
    , ""
    , "-- ---------------------------------------------------------------------------"
    , "-- Motion"
    , "-- ---------------------------------------------------------------------------"
    , ""
    ]
    ++ concatMap renderMotionDuration motionDurationData
    ++ concatMap renderMotionEasing motionEasingData
    ++
    [ "-- ---------------------------------------------------------------------------"
    , "-- Breakpoints"
    , "-- ---------------------------------------------------------------------------"
    , ""
    , "type alias Breakpoint ="
    , "    { name : String, px : Int }"
    , ""
    , "breakpoints : List Breakpoint"
    , "breakpoints ="
    , renderBreakpointList breakpoints
    , ""
    , "-- ---------------------------------------------------------------------------"
    , "-- Legacy aliases (backward compatibility with Guide.Generated)"
    , "-- ---------------------------------------------------------------------------"
    , ""
    , "featureColor : String"
    , "featureColor = colorBrandBlack"
    , ""
    , "highlightColor : String"
    , "highlightColor = colorBrandWhite"
    , ""
    , "darkBackground : String"
    , "darkBackground = colorBrandBlack"
    ]

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

unHex :: Hex -> Text
unHex (Hex t) = t

q :: Text -> Text
q t = "\"" <> escElm t <> "\""

escElm :: Text -> Text
escElm = T.concatMap c
  where
    c '\\' = "\\\\"
    c '"'  = "\\\""
    c '\n' = "\\n"
    c x    = T.singleton x

renderSemanticColor :: SemanticColorRow -> [Text]
renderSemanticColor (elmName, _, val, tw, _cssVar, desc) =
    [ ""
    , "-- " <> desc
    , elmName <> " : String"
    , elmName <> " ="
    , "    " <> q val
    , ""
    , elmName <> "Tw : String"
    , elmName <> "Tw ="
    , "    " <> q tw
    ]

renderSkinToneList :: [(Text, Text, Hex)] -> Text
renderSkinToneList [] = "    []"
renderSkinToneList items =
    T.unlines $
        ["    [ " <> renderST (head items)]
        ++ map (\i -> "    , " <> renderST i) (tail items)
        ++ ["    ]"]
  where
    renderST (i, n, Hex h) = "{ id = " <> q i <> ", name = " <> q n <> ", hex = " <> q h <> " }"

renderRainbowList :: [(Text, Text, Hex, Text)] -> Text
renderRainbowList [] = "    []"
renderRainbowList items =
    T.unlines $
        ["    [ " <> renderRC (head items)]
        ++ map (\i -> "    , " <> renderRC i) (tail items)
        ++ ["    ]"]
  where
    renderRC (i, n, Hex h, d) = "{ id = " <> q i <> ", name = " <> q n <> ", hex = " <> q h <> ", description = " <> q d <> " }"

renderTypeScaleList :: [TypeScaleRow] -> Text
renderTypeScaleList [] = "    []"
renderTypeScaleList items =
    T.unlines $
        ["    [ " <> renderTS (head items)]
        ++ map (\i -> "    , " <> renderTS i) (tail items)
        ++ ["    ]"]
  where
    renderTS (name, w, sr, sp, lh, ls, cc, d) =
        "{ name = " <> q name
        <> ", weight = " <> T.pack (show w)
        <> ", sizePx = " <> T.pack (show sp)
        <> ", sizeRem = " <> T.pack (show sr)
        <> ", lineHeight = " <> T.pack (show lh)
        <> ", letterSpacingEm = " <> T.pack (show ls)
        <> ", cssClass = " <> q cc
        <> ", description = " <> q d
        <> " }"

renderTypeHelper :: TypeScaleRow -> [Text]
renderTypeHelper (name, w, _, sp, _, _, cc, _) =
    [ ""
    , "-- " <> name <> ": " <> T.pack (show sp) <> "px / weight " <> T.pack (show w)
    , "type" <> name <> " : String"
    , "type" <> name <> " ="
    , "    " <> q cc
    , ""
    , "type" <> name <> "Weight : Int"
    , "type" <> name <> "Weight ="
    , "    " <> T.pack (show w)
    ]

renderSpacingList :: [SpacingRow] -> Text
renderSpacingList [] = "    []"
renderSpacingList items =
    T.unlines $
        ["    [ " <> renderSP (head items)]
        ++ map (\i -> "    , " <> renderSP i) (tail items)
        ++ ["    ]"]
  where
    renderSP (name, _, px, rem_, tw, d) =
        "{ name = " <> q name
        <> ", px = " <> T.pack (show px)
        <> ", rem = " <> T.pack (show rem_)
        <> ", tailwindClass = " <> q tw
        <> ", description = " <> q d
        <> " }"

renderMotionDuration :: (Text, Int, Text, Text) -> [Text]
renderMotionDuration (name, ms, _, _) =
    let helperName = "motion" <> T.toUpper (T.take 1 name) <> T.drop 1 name <> "Ms"
    in
    [ helperName <> " : Int"
    , helperName <> " ="
    , "    " <> T.pack (show ms)
    , ""
    ]

renderMotionEasing :: EasingRow -> [Text]
renderMotionEasing (name, p1x, p1y, p2x, p2y, _) =
    let helperName = "motionEasing" <> T.toUpper (T.take 1 name) <> T.drop 1 name
        cssVal = "cubic-bezier(" <> showD p1x <> ", " <> showD p1y <> ", " <> showD p2x <> ", " <> showD p2y <> ")"
    in
    [ helperName <> " : String"
    , helperName <> " ="
    , "    " <> q cssVal
    , ""
    ]
  where
    showD d = T.pack (if d == fromIntegral (round d :: Int) then show (round d :: Int) else show d)

renderBreakpointList :: [(Text, Int)] -> Text
renderBreakpointList [] = "    []"
renderBreakpointList items =
    T.unlines $
        ["    [ " <> renderBP (head items)]
        ++ map (\i -> "    , " <> renderBP i) (tail items)
        ++ ["    ]"]
  where
    renderBP (name, px) = "{ name = " <> q name <> ", px = " <> T.pack (show px) <> " }"
