module Guide.Tokens exposing (..)

-- Generated by logo-gen. Do not edit by hand.
-- Single Elm source for all brand design constants.
-- To modify: change src/Brand/Colors.hs or src/Brand/DesignData.hs, then run `make run`.

-- ---------------------------------------------------------------------------
-- Organisation
-- ---------------------------------------------------------------------------

associationName : String
associationName =
    "Suomen Palikkaharrastajat ry"

logoBaseUrl : String
logoBaseUrl =
    "https://logo.palikkaharrastajat.fi"

designGuideUrl : String
designGuideUrl =
    "/design-guide.json"

-- ---------------------------------------------------------------------------
-- Brand colors (primitive)
-- ---------------------------------------------------------------------------

colorBrandBlack : String
colorBrandBlack =
    "#05131D"

colorBrandWhite : String
colorBrandWhite =
    "#FFFFFF"

colorBrandYellow : String
colorBrandYellow =
    "#F2CD37"

-- ---------------------------------------------------------------------------
-- Semantic colors
-- ---------------------------------------------------------------------------

-- Primary body text; use on white or light-gray backgrounds.
colorTextPrimary : String
colorTextPrimary =
    "#05131D"

colorTextPrimaryTw : String
colorTextPrimaryTw =
    "text-brand"

-- Text on dark or brand-colored backgrounds.
colorTextOnDark : String
colorTextOnDark =
    "#FFFFFF"

colorTextOnDarkTw : String
colorTextOnDarkTw =
    "text-white"

-- Secondary labels, captions, helper text on light backgrounds.
colorTextMuted : String
colorTextMuted =
    "#6B7280"

colorTextMutedTw : String
colorTextMutedTw =
    "text-gray-500"

-- De-emphasised metadata; use only for large text.
colorTextSubtle : String
colorTextSubtle =
    "#9CA3AF"

colorTextSubtleTw : String
colorTextSubtleTw =
    "text-gray-400"

-- Default page/document background.
colorBgPage : String
colorBgPage =
    "#FFFFFF"

colorBgPageTw : String
colorBgPageTw =
    "bg-white"

-- Dark section backgrounds. Pair with colorTextOnDark.
colorBgDark : String
colorBgDark =
    "#05131D"

colorBgDarkTw : String
colorBgDarkTw =
    "bg-brand"

-- Light card and section backgrounds.
colorBgSubtle : String
colorBgSubtle =
    "#F9FAFB"

colorBgSubtleTw : String
colorBgSubtleTw =
    "bg-gray-50"

-- Brand accent CTA color. Always pair with colorTextPrimary.
colorBgAccent : String
colorBgAccent =
    "#F2CD37"

colorBgAccentTw : String
colorBgAccentTw =
    "bg-brand-yellow"

-- Standard card and section divider borders.
colorBorderDefault : String
colorBorderDefault =
    "#E5E7EB"

colorBorderDefaultTw : String
colorBorderDefaultTw =
    "border-gray-200"

-- Brand-colored borders, left-accent rules, focus rings.
colorBorderBrand : String
colorBorderBrand =
    "#05131D"

colorBorderBrandTw : String
colorBorderBrandTw =
    "border-brand"

-- ---------------------------------------------------------------------------
-- Skin tones
-- ---------------------------------------------------------------------------

type alias SkinTone =
    { id : String, name : String, hex : String }

skinTones : List SkinTone
skinTones =
    [ { id = "yellow", name = "Yellow", hex = "#F2CD37" }
    , { id = "light-nougat", name = "Light Nougat", hex = "#F6D7B3" }
    , { id = "nougat", name = "Nougat", hex = "#D09168" }
    , { id = "dark-nougat", name = "Dark Nougat", hex = "#AD6140" }
    ]


-- ---------------------------------------------------------------------------
-- Rainbow
-- ---------------------------------------------------------------------------

type alias RainbowColor =
    { id : String, name : String, hex : String, description : String }

rainbowColors : List RainbowColor
rainbowColors =
    [ { id = "salmon", name = "Salmon", hex = "#F2705E", description = "Red" }
    , { id = "light-orange", name = "Light Orange", hex = "#F9BA61", description = "Orange" }
    , { id = "yellow", name = "Yellow", hex = "#F2CD37", description = "Yellow" }
    , { id = "medium-green", name = "Medium Green", hex = "#73DCA1", description = "Green" }
    , { id = "bright-light-blue", name = "Bright Light Blue", hex = "#9FC3E9", description = "Blue" }
    , { id = "light-lilac", name = "Light Lilac", hex = "#9195CA", description = "Indigo" }
    , { id = "medium-lavender", name = "Medium Lavender", hex = "#AC78BA", description = "Violet" }
    ]


-- ---------------------------------------------------------------------------
-- Typography
-- ---------------------------------------------------------------------------

fontFamily : String
fontFamily =
    "Outfit, system-ui, sans-serif"

fontFile : String
fontFile =
    "/fonts/Outfit-VariableFont_wght.ttf"

type alias TypeStyle =
    { name : String
    , weight : Int
    , sizePx : Int
    , sizeRem : Float
    , lineHeight : Float
    , letterSpacingEm : Float
    , cssClass : String
    , description : String
    }

typeScale : List TypeStyle
typeScale =
    [ { name = "Display", weight = 700, sizePx = 48, sizeRem = 3.0, lineHeight = 1.1, letterSpacingEm = -2.0e-2, cssClass = "text-5xl font-bold", description = "Hero headlines and landing-page titles only." }
    , { name = "Heading1", weight = 700, sizePx = 30, sizeRem = 1.875, lineHeight = 1.2, letterSpacingEm = -1.0e-2, cssClass = "text-3xl font-bold", description = "Page-level headings (one per page)." }
    , { name = "Heading2", weight = 700, sizePx = 24, sizeRem = 1.5, lineHeight = 1.3, letterSpacingEm = 0.0, cssClass = "text-2xl font-bold", description = "Section headings." }
    , { name = "Heading3", weight = 600, sizePx = 20, sizeRem = 1.25, lineHeight = 1.35, letterSpacingEm = 0.0, cssClass = "text-xl font-semibold", description = "Sub-section headings." }
    , { name = "Body", weight = 400, sizePx = 16, sizeRem = 1.0, lineHeight = 1.6, letterSpacingEm = 0.0, cssClass = "text-base", description = "Default body copy. Minimum size for accessible reading." }
    , { name = "BodySmall", weight = 500, sizePx = 14, sizeRem = 0.875, lineHeight = 1.5, letterSpacingEm = 0.0, cssClass = "text-sm font-medium", description = "Secondary labels, UI controls, and form hints." }
    , { name = "Caption", weight = 400, sizePx = 14, sizeRem = 0.875, lineHeight = 1.4, letterSpacingEm = 2.0e-2, cssClass = "text-sm", description = "Image captions, footnotes, and metadata." }
    , { name = "Mono", weight = 400, sizePx = 14, sizeRem = 0.875, lineHeight = 1.6, letterSpacingEm = 0.0, cssClass = "font-mono text-sm", description = "Hex values, IDs, and code snippets." }
    , { name = "Overline", weight = 600, sizePx = 12, sizeRem = 0.75, lineHeight = 1.4, letterSpacingEm = 8.0e-2, cssClass = "text-xs font-semibold uppercase tracking-wider", description = "Section category labels. Always uppercase." }
    ]


-- Display: 48px / weight 700
typeDisplay : String
typeDisplay =
    "text-5xl font-bold"

typeDisplayWeight : Int
typeDisplayWeight =
    700

-- Heading1: 30px / weight 700
typeHeading1 : String
typeHeading1 =
    "text-3xl font-bold"

typeHeading1Weight : Int
typeHeading1Weight =
    700

-- Heading2: 24px / weight 700
typeHeading2 : String
typeHeading2 =
    "text-2xl font-bold"

typeHeading2Weight : Int
typeHeading2Weight =
    700

-- Heading3: 20px / weight 600
typeHeading3 : String
typeHeading3 =
    "text-xl font-semibold"

typeHeading3Weight : Int
typeHeading3Weight =
    600

-- Body: 16px / weight 400
typeBody : String
typeBody =
    "text-base"

typeBodyWeight : Int
typeBodyWeight =
    400

-- BodySmall: 14px / weight 500
typeBodySmall : String
typeBodySmall =
    "text-sm font-medium"

typeBodySmallWeight : Int
typeBodySmallWeight =
    500

-- Caption: 14px / weight 400
typeCaption : String
typeCaption =
    "text-sm"

typeCaptionWeight : Int
typeCaptionWeight =
    400

-- Mono: 14px / weight 400
typeMono : String
typeMono =
    "font-mono text-sm"

typeMonoWeight : Int
typeMonoWeight =
    400

-- Overline: 12px / weight 600
typeOverline : String
typeOverline =
    "text-xs font-semibold uppercase tracking-wider"

typeOverlineWeight : Int
typeOverlineWeight =
    600

-- ---------------------------------------------------------------------------
-- Spacing
-- ---------------------------------------------------------------------------

spacingBaseUnit : Int
spacingBaseUnit =
    4

type alias SpacingStep =
    { name : String, px : Int, rem : Float, tailwindClass : String, description : String }

spacingScale : List SpacingStep
spacingScale =
    [ { name = "space-1", px = 4, rem = 0.25, tailwindClass = "p-1 / m-1", description = "Tight: icon padding, inline gaps." }
    , { name = "space-2", px = 8, rem = 0.5, tailwindClass = "p-2 / m-2", description = "Compact: button padding, tag gaps." }
    , { name = "space-3", px = 12, rem = 0.75, tailwindClass = "p-3 / m-3", description = "Small: input padding, list item gaps." }
    , { name = "space-4", px = 16, rem = 1.0, tailwindClass = "p-4 / m-4", description = "Base: card padding, form field gaps." }
    , { name = "space-6", px = 24, rem = 1.5, tailwindClass = "p-6 / m-6", description = "Medium: section sub-divisions." }
    , { name = "space-8", px = 32, rem = 2.0, tailwindClass = "p-8 / m-8", description = "Large: card body padding, section gaps." }
    , { name = "space-12", px = 48, rem = 3.0, tailwindClass = "p-12 / m-12", description = "XL: page section vertical margins." }
    , { name = "space-16", px = 64, rem = 4.0, tailwindClass = "p-16 / m-16", description = "2XL: hero and feature block spacing." }
    ]


pageWrapper : String
pageWrapper =
    "max-w-5xl mx-auto px-4"

-- ---------------------------------------------------------------------------
-- Motion
-- ---------------------------------------------------------------------------

motionFastMs : Int
motionFastMs =
    150

motionBaseMs : Int
motionBaseMs =
    300

motionSlowMs : Int
motionSlowMs =
    500

motionLogoFrameMs : Int
motionLogoFrameMs =
    10000

motionEasingStandard : String
motionEasingStandard =
    "cubic-bezier(0.4, 0, 0.2, 1)"

motionEasingDecelerate : String
motionEasingDecelerate =
    "cubic-bezier(0, 0, 0.2, 1)"

motionEasingAccelerate : String
motionEasingAccelerate =
    "cubic-bezier(0.4, 0, 1, 1)"

-- ---------------------------------------------------------------------------
-- Breakpoints
-- ---------------------------------------------------------------------------

type alias Breakpoint =
    { name : String, px : Int }

breakpoints : List Breakpoint
breakpoints =
    [ { name = "sm", px = 640 }
    , { name = "md", px = 768 }
    , { name = "lg", px = 1024 }
    , { name = "xl", px = 1280 }
    ]


-- ---------------------------------------------------------------------------
-- Legacy aliases (backward compatibility with Guide.Generated)
-- ---------------------------------------------------------------------------

featureColor : String
featureColor = colorBrandBlack

highlightColor : String
highlightColor = colorBrandWhite

darkBackground : String
darkBackground = colorBrandBlack
